In [116]:
import pandas as pd;
import json
import re

In [117]:
df_dirty = pd.read_json("../data/raw/appdetails.json");


display(df_dirty.head(5));
display(df_dirty[df_dirty['success'] == False])

     appid  success                                               data
0      620     True  {'type': 'game', 'name': 'Portal 2', 'steam_ap...
1   413150     True  {'type': 'game', 'name': 'Stardew Valley', 'st...
2  1118200     True  {'type': 'game', 'name': 'People Playground', ...
3      400     True  {'type': 'game', 'name': 'Portal', 'steam_appi...
4  1794680     True  {'type': 'game', 'name': 'Vampire Survivors', ...

       appid  success data
152   217980    False  NaN
551  1161870    False  NaN
878  1903370    False  NaN

In [ ]:
rows = []
with open("../data/raw/appdetails.json", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        
        item = json.loads(line)
        
        # Se o arquivo contiver listas de itens por linha, tratamos cada um:
        items_list = item if isinstance(item, list) else [item]
        
        for sub_item in items_list:
            if isinstance(sub_item, dict) and sub_item.get("success") and "data" in sub_item:
                row = sub_item["data"]
                row["appid"] = sub_item.get("appid")
                rows.append(row)

# Converte a lista de dicionários em um DataFrame estruturado
df_normalized_dirty = pd.DataFrame(rows)

# Exibe as primeiras linhas com as colunas abertas
display(df_normalized_dirty[['name', 'type', 'is_free', 'required_age']].head(5))

pd.set_option('display.max_columns', None)

display(df_normalized_dirty.head(1))

                name  type  is_free required_age
0           Portal 2  game    False            0
1     Stardew Valley  game    False           12
2  People Playground  game    False            0
3             Portal  game    False            0
4  Vampire Survivors  game    False            0

,type,name,steam_appid,required_age,is_free,controller_support,dlc,detailed_description,about_the_game,short_description,supported_languages,header_image,capsule_image,capsule_imagev5,website,pc_requirements,mac_requirements,linux_requirements,developers,publishers,price_overview,packages,package_groups,platforms,metacritic,categories,genres,screenshots,movies,recommendations,achievements,release_date,support_info,background,background_raw,content_descriptors,ratings,appid,reviews,demos,legal_notice,ext_user_account_notice,fullgame,drm_notice
0,game,Portal 2,620,0,False,full,[323180],Portal 2 draws from the award-winning formula ...,Portal 2 draws from the award-winning formula ...,The &quot;Perpetual Testing Initiative&quot; h...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,http://www.thinkwithportals.com/,{'minimum': '<strong>Minimum:</strong><br><ul ...,{'minimum': '<strong>Minimum:</strong><br><ul ...,{'minimum': '<strong>Minimum:</strong><br><ul ...,[Valve],[Valve],"{'currency': 'BRL', 'initial': 3299, 'final': ...","[204528, 7877, 8187]","[{'name': 'default', 'title': 'Buy Portal 2', ...","{'windows': True, 'mac': False, 'linux': True}","{'score': 95, 'url': 'https://www.metacritic.c...","[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}, {'id': ...","[{'id': 0, 'path_thumbnail': 'https://shared.a...","[{'id': 5787, 'name': 'Portal 2 E3 Demo (Excur...",{'total': 390616},"{'total': 51, 'highlighted': [{'icon': 'SURVIV...","{'coming_soon': False, 'date': '18 Apr, 2011'}","{'url': 'http://steamcommunity.com/app/620', '...",https://store.akamai.steamstatic.com/images/st...,https://store.akamai.steamstatic.com/images/st...,"{'ids': [], 'notes': None}","{'usk': {'rating': '12'}, 'dejus': {'rating_ge...",620,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
display(df_normalized_dirty[df_normalized_dirty["name"].str.lower().str.startswith("the wi", na=False)])
pd.set_option('display.max_columns', 22)

,type,name,steam_appid,required_age,is_free,controller_support,dlc,detailed_description,about_the_game,short_description,supported_languages,header_image,capsule_image,capsule_imagev5,website,pc_requirements,mac_requirements,linux_requirements,developers,publishers,price_overview,packages,package_groups,platforms,metacritic,categories,genres,screenshots,movies,recommendations,achievements,release_date,support_info,background,background_raw,content_descriptors,ratings,appid,reviews,demos,legal_notice,ext_user_account_notice,fullgame,drm_notice
122,game,The Witcher 3: Wild Hunt - Complete Edition,292030,17,False,NaN,"[5006530, 1229320, 1233280, 1233340]",<h1>GET READY FOR AN EPIC WITCHER STORY FULL O...,"<p class=""bb_paragraph"" style=""text-align: cen...","You are Geralt of Rivia, mercenary monster sla...","English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,https://www.thewitcher.com/witcher3,{'minimum': '<strong>Minimum:</strong><br><ul ...,[],[],[CD PROJEKT RED],[CD PROJEKT RED],"{'currency': 'USD', 'initial': 4999, 'final': ...",[68476],"[{'name': 'default', 'title': 'Buy The Witcher...","{'windows': True, 'mac': False, 'linux': False}","{'score': 93, 'url': 'https://www.metacritic.c...","[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '3', 'description': 'RPG'}]","[{'id': 0, 'path_thumbnail': 'https://shared.a...","[{'id': 257411256, 'name': 'The Witcher 3: Wil...",{'total': 833494},"{'total': 78, 'highlighted': [{'icon': '607858...","{'coming_soon': False, 'date': 'May 18, 2015'}","{'url': 'http://en.cdprojektred.com/support', ...",https://store.akamai.steamstatic.com/images/st...,https://shared.akamai.steamstatic.com/store_it...,"{'ids': [1, 5], 'notes': 'The Witcher 3: Wild ...","{'esrb': {'rating': 'm', 'descriptors': 'Blood...",292030,“ONE OF THE BEST GAMES EVER MADE”<br>10/10 – G...,NaN,"CD PROJEKT RED®, CD PROJEKT®, The Witcher® are...",NaN,NaN,NaN
446,dlc,The Witcher 3: Wild Hunt - Blood and Wine,378648,0,False,full,NaN,"<h1>Special Offer</h1><p><span class=""bb_img_c...",Blood and Wine is the final expansion for The ...,Become professional monster slayer Geralt of R...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,http://www.thewitcher.com,{'minimum': '<strong>Minimum:</strong><br><ul ...,[],[],[CD PROJEKT RED],[CD PROJEKT RED],NaN,NaN,[],"{'windows': True, 'mac': False, 'linux': False}","{'score': 92, 'url': 'https://www.metacritic.c...","[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '3', 'description': 'RPG'}]","[{'id': 0, 'path_thumbnail': 'https://shared.a...","[{'id': 256664412, 'name': 'Trailer', 'thumbna...",{'total': 9327},NaN,"{'coming_soon': False, 'date': '30 May, 2016'}","{'url': 'http://en.cdprojektred.com/support', ...",https://store.akamai.steamstatic.com/images/st...,https://shared.akamai.steamstatic.com/store_it...,"{'ids': [1, 5], 'notes': 'The Witcher 3: Wild ...","{'pegi': {'rating': '18'}, 'oflc': {'rating': ...",378648,NaN,NaN,"CD PROJEKT®, The Witcher® are registered trade...",NaN,"{'appid': '292030', 'name': 'The Witcher 3: Wi...",NaN
878,dlc,The Witcher 3: Wild Hunt - Expansion Pass,355880,0,False,full,NaN,The Expansion Pass secures your access to two ...,The Expansion Pass secures your access to two ...,The Witcher 3: Wild Hunt Expansion Pass secure...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,https://shared.akamai.steamstatic.com/store_it...,http://www.thewitcher.com,{'minimum': '<strong>Minimum:</strong><br><ul ...,{'minimum': '<strong>Minimum:</strong><br><ul ...,{'minimum': '<strong>Minimum:</strong><br><ul ...,[CD PROJEKT RED],[CD PROJEKT RED],NaN,NaN,[],"{'windows': True, 'mac': False, 'linux': False}",NaN,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '3', 'description': 'RPG'}]","[{'id': 0, 'path_thumbnail': 'https://shared.a...","[{'id': 256658627, 'name': 'Expansion Pass Tra...",{'total': 4525},NaN,"{'coming_soon': False, 'date': '19 May, 2015'}",{'url': 'http://en.cdprojektred.com/support-pr...,https://store.akamai.steamstatic.com/images/st...,https://store.akamai.steamstatic.com/images/st...,"{'ids': [1, 5], 'notes': None}",None,355880,NaN,NaN,"CD PROJEKT®, The Witcher® are registered trade...",NaN,"{'appid': '292030', 'name': 'The Witcher 3: Wi...",NaN

In [ ]:
df_colunas_filtradas = df_normalized_dirty[['type', 'name', 'required_age', 'is_free', 'dlc','packages','controller_support',
                                            'developers', 'publishers', 'pc_requirements', 'price_overview', 'metacritic',  
                                            'categories', 'genres', 'recommendations', 'achievements', 'release_date', 'ratings', 'supported_languages']]

# formatando colunas

df_colunas_filtradas['developers'] = df_colunas_filtradas['developers'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else str(x) if pd.notna(x) else ''
)

df_colunas_filtradas['publishers'] = df_colunas_filtradas['publishers'].apply(
    lambda x: ', '.join(x) if isinstance(x, list) else str(x) if pd.notna(x) else ''
)

df_colunas_filtradas['metacritic'] = df_colunas_filtradas['metacritic'].apply(
    lambda x: x.get('score') if isinstance(x, dict) else None
)

df_colunas_filtradas['recommendations'] = df_colunas_filtradas['recommendations'].apply(
    lambda x: x.get('total') if isinstance(x, dict) else None
).astype('Int64')

df_colunas_filtradas['release_date'] = df_colunas_filtradas['release_date'].apply(
    lambda x: x.get('date') if isinstance(x, dict) else None
)

df_colunas_filtradas['achievements'] = df_colunas_filtradas['achievements'].apply(
    lambda x: x.get('total') if isinstance(x, dict) else None
).astype('Int64')

# Função para extrair as 'description' e juntar com vírgula
def extrair_descriptions(x):
    if isinstance(x, list):
        # Percorre a lista, pega o valor de 'description' se for dicionário e junta com ', '
        return ', '.join([item.get('description', '') for item in x if isinstance(item, dict) and 'description' in item])
    return ''

# Aplica a transformação nas colunas genres e categories
df_colunas_filtradas['genres'] = df_colunas_filtradas['genres'].apply(extrair_descriptions)
df_colunas_filtradas['categories'] = df_colunas_filtradas['categories'].apply(extrair_descriptions);

import re

def limpar_idiomas(texto):
    if isinstance(texto, str):
        # 1. Remove as tags HTML (ex: <strong>, </strong>)
        texto_sem_html = re.sub(r'<[^>]*>', '', texto)
        # 2. Remove o asterisco (*) e eventuais espaços extras ao redor dele
        texto_limpo = re.sub(r'\s*\*+', '', texto_sem_html)
        return texto_limpo.strip()
    return texto

# Aplica a limpeza na coluna supported_languages
df_colunas_filtradas['supported_languages'] = df_colunas_filtradas['supported_languages'].apply(limpar_idiomas)



def contar_itens(x):
    if isinstance(x, list):
        return len(x)
    return 0 

if 'dlc' in df_colunas_filtradas.columns:
    df_colunas_filtradas['dlc'] = df_colunas_filtradas['dlc'].apply(contar_itens).astype('Int64')

if 'packages' in df_colunas_filtradas.columns:
    df_colunas_filtradas['packages'] = df_colunas_filtradas['packages'].apply(contar_itens).astype('Int64')

display(df_colunas_filtradas.head(7))

,type,name,required_age,is_free,dlc,packages,controller_support,developers,publishers,pc_requirements,price_overview,metacritic,categories,genres,recommendations,achievements,release_date,ratings,supported_languages
0,game,Portal 2,0,False,1,3,full,Valve,Valve,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 3299, 'final': ...",95.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Adventure",390616,51,"18 Apr, 2011","{'usk': {'rating': '12'}, 'dejus': {'rating_ge...","English, French, German, Spanish - Spain, Czec..."
1,game,Stardew Valley,12,False,1,2,full,ConcernedApe,ConcernedApe,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 2499, 'final': ...",89.0,"Single-player, Multi-player, Co-op, Online Co-...","Indie, RPG, Simulation",894890,49,"26 Feb, 2016","{'esrb': {'rating': 'e10', 'descriptors': 'Fan...","English, German, Spanish - Spain, Japanese, Po..."
2,game,People Playground,0,False,0,1,NaN,mestiez,Studio Minus,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 2069, 'final': ...",NaN,"Single-player, Steam Achievements, Steam Tradi...","Action, Casual, Indie, Simulation",298348,17,"23 Jul, 2019","{'dejus': {'rating': '16', 'descriptors': 'Vio...",English
3,game,Portal,0,False,2,3,full,Valve,Valve,{'minimum': ' <p><strong>Minimum: </strong>...,"{'currency': 'BRL', 'initial': 3299, 'final': ...",90.0,"Single-player, Steam Achievements, Full contro...",Action,173695,15,"10 Oct, 2007","{'usk': {'rating': '12'}, 'dejus': {'rating': ...","English, French, German, Russian, Danish, Dutc..."
4,game,Vampire Survivors,0,False,9,1,full,poncle,poncle,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'USD', 'initial': 499, 'final': 4...",86.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Casual, Indie, RPG",251776,243,"Oct 20, 2022","{'dejus': {'rating': '10', 'descriptors': 'Vio...","English, French, Italian, German, Spanish - Sp..."
5,game,HoloCure - Save the Fans!,0,True,0,0,NaN,KayAnimate,KayAnimate,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,NaN,"Single-player, Steam Achievements, Gamepad Rec...","Action, Adventure, Casual, Indie",<NA>,97,"16 Aug, 2023","{'dejus': {'rating_generated': '1', 'rating': ...","English, Japanese"
6,game,Hades,0,False,1,1,full,Supergiant Games,Supergiant Games,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'USD', 'initial': 2499, 'final': ...",93.0,"Single-player, Steam Achievements, Full contro...","Action, Indie, RPG",285838,49,"Sep 17, 2020","{'dejus': {'rating': '14', 'descriptors': 'Vio...","English, French, Italian, German, Spanish - Sp..."

In [ ]:



df_colunas_filtradas['required_age'] = pd.to_numeric(df_colunas_filtradas['required_age'], errors='coerce').fillna(0).astype('Int64')

#  Cria uma função ou lógica para extrair a idade do dejus da coluna 'ratings'
def extrair_idade_dejus(ratings):
    if isinstance(ratings, dict):
        dejus_info = ratings.get('dejus')
        if isinstance(dejus_info, dict):
            # Tenta pegar 'required_age' ou 'rating' do dejus
            idade = dejus_info.get('required_age') or dejus_info.get('rating')
            if idade is not None:
                return pd.to_numeric(idade, errors='coerce')
    return None

#  Aplica a substituição: onde required_age for 0, substitui pela idade do dejus (se houver)
mascara_zero = (df_colunas_filtradas['required_age'] == 0) | (df_colunas_filtradas['required_age'].isna())

df_colunas_filtradas.loc[mascara_zero, 'required_age'] = df_colunas_filtradas.loc[mascara_zero, 'ratings'].apply(extrair_idade_dejus)

# Converte definitivamente para inteiro com suporte a nulos no final
df_colunas_filtradas['required_age'] = pd.to_numeric(df_colunas_filtradas['required_age'], errors='coerce').astype('Int64')

display(df_colunas_filtradas.head(10))

,type,name,required_age,is_free,dlc,packages,controller_support,developers,publishers,pc_requirements,price_overview,metacritic,categories,genres,recommendations,achievements,release_date,ratings,supported_languages
0,game,Portal 2,12,False,1,3,full,Valve,Valve,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 3299, 'final': ...",95.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Adventure",390616,51,"18 Apr, 2011","{'usk': {'rating': '12'}, 'dejus': {'rating_ge...","English, French, German, Spanish - Spain, Czec..."
1,game,Stardew Valley,12,False,1,2,full,ConcernedApe,ConcernedApe,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 2499, 'final': ...",89.0,"Single-player, Multi-player, Co-op, Online Co-...","Indie, RPG, Simulation",894890,49,"26 Feb, 2016","{'esrb': {'rating': 'e10', 'descriptors': 'Fan...","English, German, Spanish - Spain, Japanese, Po..."
2,game,People Playground,16,False,0,1,NaN,mestiez,Studio Minus,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 2069, 'final': ...",NaN,"Single-player, Steam Achievements, Steam Tradi...","Action, Casual, Indie, Simulation",298348,17,"23 Jul, 2019","{'dejus': {'rating': '16', 'descriptors': 'Vio...",English
3,game,Portal,10,False,2,3,full,Valve,Valve,{'minimum': ' <p><strong>Minimum: </strong>...,"{'currency': 'BRL', 'initial': 3299, 'final': ...",90.0,"Single-player, Steam Achievements, Full contro...",Action,173695,15,"10 Oct, 2007","{'usk': {'rating': '12'}, 'dejus': {'rating': ...","English, French, German, Russian, Danish, Dutc..."
4,game,Vampire Survivors,10,False,9,1,full,poncle,poncle,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'USD', 'initial': 499, 'final': 4...",86.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Casual, Indie, RPG",251776,243,"Oct 20, 2022","{'dejus': {'rating': '10', 'descriptors': 'Vio...","English, French, Italian, German, Spanish - Sp..."
5,game,HoloCure - Save the Fans!,10,True,0,0,NaN,KayAnimate,KayAnimate,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,NaN,"Single-player, Steam Achievements, Gamepad Rec...","Action, Adventure, Casual, Indie",<NA>,97,"16 Aug, 2023","{'dejus': {'rating_generated': '1', 'rating': ...","English, Japanese"
6,game,Hades,10,False,1,1,full,Supergiant Games,Supergiant Games,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'USD', 'initial': 2499, 'final': ...",93.0,"Single-player, Steam Achievements, Full contro...","Action, Indie, RPG",285838,49,"Sep 17, 2020","{'dejus': {'rating': '14', 'descriptors': 'Vio...","English, French, Italian, German, Spanish - Sp..."
7,game,The Henry Stickmin Collection,12,False,0,1,NaN,PuffballsUnited,Innersloth,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'USD', 'initial': 1499, 'final': ...",NaN,"Single-player, Steam Achievements, Captions av...","Adventure, Casual, Indie",55877,82,"7 Aug, 2020","{'dejus': {'rating': '12', 'descriptors': 'Vio...",Englishlanguages with full audio support
8,game,Wallpaper Engine,0,False,1,1,NaN,Wallpaper Engine Team,Wallpaper Engine Team,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'VND', 'initial': 7500000, 'final...",NaN,"Steam Achievements, Steam Trading Cards, Steam...","Casual, Indie, Animation & Modeling, Design & ...",945528,17,"16 Nov, 2018","{'dejus': {'rating_generated': '1', 'rating': ...","English, German, Simplified Chinese, Polish, P..."
9,game,Left 4 Dead 2,14,False,0,2,full,Valve,Valve,{'minimum': '<strong>Minimum:</strong><br><ul ...,"{'currency': 'BRL', 'initial': 3299, 'final': ...",89.0,"Single-player, Multi-player, PvP, Online PvP, ...",Action,816863,101,"16 Nov, 2009","{'oflc': {'rating': 'r18', 'use_age_gate': 'tr...","Danish, Dutch, English, Finnish, French, Germa..."

In [ ]:


df_sem_ratings = df_colunas_filtradas.drop(columns=['ratings'])

moedas_presentes = df_sem_ratings['price_overview'].apply(
    lambda x: x.get('currency') if isinstance(x, dict) else None
).dropna().unique()

print(moedas_presentes)

<StringArray>
['BRL', 'USD', 'VND', 'CAD', 'EUR', 'GBP', 'INR', 'PHP', 'CHF', 'COP', 'PEN',
 'HKD', 'AUD', 'SGD', 'NOK', 'ZAR']
Length: 16, dtype: str

In [137]:

# Dicionário de taxas de câmbio para BRL
taxas_para_brl = {
    'BRL': 1.00,    # Real Brasileiro (base)
    'USD': 5.50,    # Dólar Americano
    'EUR': 6.00,    # Euro
    'GBP': 7.00,    # Libra Esterlina
    'CHF': 6.20,    # Franco Suíço
    'CAD': 4.00,    # Dólar Canadense
    'AUD': 3.60,    # Dólar Australiano
    'SGD': 4.10,    # Dólar de Singapura
    'PEN': 1.50,    # Sol Peruano
    'HKD': 0.70,    # Dólar de Hong Kong
    'NOK': 0.50,    # Coroa Norueguesa
    'ZAR': 0.30,    # Rand Sul-Africano
    'PHP': 0.10,    # Peso Filipino
    'INR': 0.065,   # Rupia Indiana
    'COP': 0.0014,  # Peso Colombiano
    'VND': 0.00022  # Dong Vietnamita
}

# Função segura para converter o preço
def converter_para_brl(row):
    if isinstance(row, dict):
        preco = row.get('initial')
        if preco is None:
            return None
        
        moeda = row.get('currency', 'BRL')
        taxa = taxas_para_brl.get(moeda, 1.0)
        
        return (preco / 100) * taxa
    return None

# Função para verificar se a moeda era diferente de BRL (se precisou de conversão real)
def foi_convertido(row):
    if isinstance(row, dict):
        moeda = row.get('currency')
        if moeda:
            # Retorna True se a moeda for diferente de BRL, False caso contrário
            return moeda != 'BRL'
    return None


df_precos_convertidos =  df_sem_ratings.copy()

df_precos_convertidos['price_brl'] = df_precos_convertidos['price_overview'].apply(converter_para_brl).round(2)

df_precos_convertidos['preco_alterado'] = df_precos_convertidos['price_overview'].apply(foi_convertido).astype('boolean')

df_precos_convertidos = df_precos_convertidos.drop(columns=['price_overview'])

display(df_precos_convertidos.head(10))

,type,name,required_age,is_free,dlc,packages,controller_support,developers,publishers,pc_requirements,metacritic,categories,genres,recommendations,achievements,release_date,supported_languages,price_brl,preco_alterado
0,game,Portal 2,12,False,1,3,full,Valve,Valve,{'minimum': '<strong>Minimum:</strong><br><ul ...,95.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Adventure",390616,51,"18 Apr, 2011","English, French, German, Spanish - Spain, Czec...",32.99,False
1,game,Stardew Valley,12,False,1,2,full,ConcernedApe,ConcernedApe,{'minimum': '<strong>Minimum:</strong><br><ul ...,89.0,"Single-player, Multi-player, Co-op, Online Co-...","Indie, RPG, Simulation",894890,49,"26 Feb, 2016","English, German, Spanish - Spain, Japanese, Po...",24.99,False
2,game,People Playground,16,False,0,1,NaN,mestiez,Studio Minus,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,"Single-player, Steam Achievements, Steam Tradi...","Action, Casual, Indie, Simulation",298348,17,"23 Jul, 2019",English,20.69,False
3,game,Portal,10,False,2,3,full,Valve,Valve,{'minimum': ' <p><strong>Minimum: </strong>...,90.0,"Single-player, Steam Achievements, Full contro...",Action,173695,15,"10 Oct, 2007","English, French, German, Russian, Danish, Dutc...",32.99,False
4,game,Vampire Survivors,10,False,9,1,full,poncle,poncle,{'minimum': '<strong>Minimum:</strong><br><ul ...,86.0,"Single-player, Multi-player, Co-op, Online Co-...","Action, Casual, Indie, RPG",251776,243,"Oct 20, 2022","English, French, Italian, German, Spanish - Sp...",27.44,True
5,game,HoloCure - Save the Fans!,10,True,0,0,NaN,KayAnimate,KayAnimate,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,"Single-player, Steam Achievements, Gamepad Rec...","Action, Adventure, Casual, Indie",<NA>,97,"16 Aug, 2023","English, Japanese",NaN,<NA>
6,game,Hades,10,False,1,1,full,Supergiant Games,Supergiant Games,{'minimum': '<strong>Minimum:</strong><br><ul ...,93.0,"Single-player, Steam Achievements, Full contro...","Action, Indie, RPG",285838,49,"Sep 17, 2020","English, French, Italian, German, Spanish - Sp...",137.44,True
7,game,The Henry Stickmin Collection,12,False,0,1,NaN,PuffballsUnited,Innersloth,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,"Single-player, Steam Achievements, Captions av...","Adventure, Casual, Indie",55877,82,"7 Aug, 2020",Englishlanguages with full audio support,82.44,True
8,game,Wallpaper Engine,0,False,1,1,NaN,Wallpaper Engine Team,Wallpaper Engine Team,{'minimum': '<strong>Minimum:</strong><br><ul ...,NaN,"Steam Achievements, Steam Trading Cards, Steam...","Casual, Indie, Animation & Modeling, Design & ...",945528,17,"16 Nov, 2018","English, German, Simplified Chinese, Polish, P...",16.50,True
9,game,Left 4 Dead 2,14,False,0,2,full,Valve,Valve,{'minimum': '<strong>Minimum:</strong><br><ul ...,89.0,"Single-player, Multi-player, PvP, Online PvP, ...",Action,816863,101,"16 Nov, 2009","Danish, Dutch, English, Finnish, French, Germa...",32.99,False